# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to get the double of the value
#' 
#' Calculating the double of x, i.e. x times 2
#' 
#' @param x A single value.
#' @return y A single value, double of x
#' @export
timesTwo <- function(x) {
    .Call('testrcpp_timesTwo', PACKAGE = 'testrcpp', x)
}

#' Example 1 Vector Input Scalar Output
#' 
#' Calculate mean of a numeric vector
#' 
#' @param x A numeric vector
#' @return y A double as mean
#' @export
meancpp <- function(x) {
    .Call('testrcpp_meancpp', PACKAGE = 'testrcpp', x)
}

